Ericsson/CodecheckerVSCodePlugin

- src/backend/processor/metadata.ts
- src/sidebar/views/reports.ts
A couple of minor fixes.
* Fix extension crash when no workspace is opened
* Reports tab hides when there's no metadata, but a file is opened
> Minor fixes

- README.md
- package.json
- src/backend/executor/process.ts
- src/backend/executor/triggers.ts
- src/editor/editor.ts
- src/editor/initialize.ts
- src/sidebar/views/overview.ts
Closes #15.
Currently the database setup dialog has 3 options:
* `Run CodeChecker log` creates a terminal, with a pre-defined `CodeChecker log` command already written there.
* `Locate` shows a file selector to select the database's path, eg. for CMake with a `/build` folder
* `Don't show again` never shows the window again on folder open.
The dialog shows when compile_commands.json is not found.
There's also a button in the Overview in an empty folder to select its path.
Currently there's no separation between missing the metadata.json and missing the compile_commands.json in the sidepanel.
I'd like to add a separate sidebar panel option for it before merging.
> Add selector for `compile_commands.json`

- src/backend/processor/diagnostics.ts
- src/backend/processor/metadata.ts
> See: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables
> Fix unknown variable types at exceptions

- README.md
- package.json
- src/editor/codelens.ts
- src/editor/editor.ts
Adds CodeLens to the reproduction path in the editor, making the flow much clearer.
> CodeLens support for repr. path

- README.md
- src/backend/executor/bridge.ts
`6.18.1` CodeChecker contained a couple of bugs which were fixed in the `6.18.2` bug fix release. With this patch we will change the minimum required CodeChecker version from `6.18.1` to `6.18.2`.
> Change minimum supported CodeChecker version to 6.18.2

- .github/workflows/deploy.yml
- README.md
Use matrix strategy in `deploy.yml` github action to create and publish
package to `OpenVSX` and `Visual Studio Marketplace`.
It will use the following unique extension ids for registries:
- `OpenVSX`: `codechecker`
- `VS Marketplace`: `vscode-codechecker`
**Note**: unfortunately we can't use the same extension id for these two
registries because will get the following error message when the package
is published to the registry:
`The Extension Id already exist in the Marketplace. Please use the different Id`
Both package will be published under the `codechecker` organization.
> Use matrix strategy at deploy github action

- package.json
- yarn.lock
`fast-plist` dependency is not used anymore (we are using `CodeChecker parse` command to process analyzer result files) so we can remove it.
> Remove `fast-plist` dependency

- src/editor/initialize.ts
> Closes #50
Wait some time until the terminal is initialized properly when getting `CodeChecker log` command.
For now there is no elegant solution for this problem than to wait some time by using `setTimeout` function.
> Wait for terminal initialization for CodeChecker log command

- src/backend/processor/diagnostics.ts
When pressing Reload CodeChecker metadata many times, many instances of the currently opened report's file are getting added to the currently open files due to a pass-by-reference bug.
> Fix adding selectedEntry to openedFiles

- src/backend/processor/diagnostics.ts
Fixes #39.
The extension no longer executes a parse call when:
* Open files did not change
* There are no files open
* A changed window has 'output://' scheme - ref: #13
> Reduce number of `parse` calls

- src/backend/executor/process.ts
- src/editor/executor.ts
- src/sidebar/views/overview.ts
> Closes #61
On large projects the analysis may take minutes. In this case it is
really annyoing for the user to show an unclosable pop-window.
Also this information whether an analysis is running is already available
in the bottom bar.
This patch will remove this pop-up window but will introduce a new tree
item on the overview sidebar to stop the analysis.
> Remove unclosable CodeChecker analysis in progress window

- src/backend/executor/bridge.ts
Check supported CodeChecker version when the CodeChecker executable path configuration setting is changed.
> Check supported CodeChecker version on configuration change

- src/editor/diagnostics.ts
> Closes #49
- Show reports as separate diagnostic items and show bug steps as diagnostic
related information.
- Show different severities based on the CodeChecker severity level.
- Refactoring the code.
Screenshot:
> Fix showing diagnostics in the Problems pane

- package.json
The next release will contain not only bug fixes but other improvements as well. So for this reason the next version should be `1.2.0` instead of `1.1.1`.
> Bump up version to 1.2.0

- src/editor/navigation.ts
> Fix keyboard navigation commands

- src/backend/executor/bridge.ts
- src/backend/processor/metadata.ts
> Closes #89
`.codechecker` directory may contain compilation database which is generated by the `CodeChecker log` command. It may also contain other files in the future. For this reason I recommend to change the output folder of the `CodeChecker analyze` command to `.codechecker/reports`.
> Change CodeChecker analysis output to .codechecker/reports

- src/editor/diagnostics.ts
> Closes #16
A `TextDocument` has a method to get word range at a given position
called `getWordRangeAtPosition`. If no range information is available
for a report we can use this method to get word position at the given
line + column position.
> Better range positions for reports

- src/editor/codelens.ts
- src/editor/diagnostics.ts
If there are unpersisted changes in the current document we will hide the provided codelens items and bug step decorations.
> Hide codelens and bug step decorations when document is dirty

- README.md
- package.json
- src/backend/executor/bridge.ts
- src/backend/executor/process.ts
- src/editor/executor.ts
- src/editor/initialize.ts
- src/utils/config.ts
- yarn.lock
Closes #56.
Previously, we `.join(' ')`-ed the executor arguments. With this refactor, the executor no longer constructs the full command-line, but rather directly passes the args array to `child_process.spawn`.
For the user-facing input (arguments setting) and output (command-line preview), the [`shell-quote`](https://www.npmjs.com/package/shell-quote) package is used.
> Refactor executor to pass shell arguments as array

- src/backend/executor/process.ts
When an exception happens during calling the `CodeChecker analyzer-version`
command we print out the process type value. It is missleading to print out
that `CodeChecker version` is failed because we have called the
`CodeChecker analyzer-version`. For this reason in this commit we change
the value of this process type.
> Change value of version process type to analyzer-version

- src/backend/executor/process.ts
We are using `spawn` method to execute a CodeChecker command.
If the executable path starts with a `~` (e.g.: `~/CodeChecker/bin/CodeChecker`),
the `spawn` method doesn't work properly and will give an exception.
For more information see: nodejs/node#684
To solve this problem we will expand the `~` in the file path before
executing the command.
> Expand user in the CodeChecker binary path

- src/backend/executor/process.ts
Fixes #73.
Currently uses the full serialized commandline for the source of deduplication, and kills for the currently running task when it's the same.
> Deduplicate scheduled tasks based on command line

- src/editor/navigation.ts
- src/test/editor/editor.functional.test.ts
- src/test/staticFiles/workspace/file.cpp
- src/test/staticFiles/workspace/file.h
Fixes #86.
The previously jumped-to step is stored, and future keyboard navigation will be based on that step.
Falls back to the old mechanism when there's no jumped-to step yet.
> Refactor keyboard navigation

- package.json
- src/backend/executor/bridge.ts
- src/backend/executor/process.ts
- src/editor/editor.ts
- src/editor/executor.ts
- src/editor/initialize.ts
- src/editor/tasks.ts
- src/sidebar/views/overview.ts
- src/test/executor/executor.functional.test.ts
- src/test/runTest.ts
- src/utils/config.ts
Fixes #38.
Instead of running `CodeChecker log` as a separate process, it is now integrated into the `backend/executor.
* Added commands, build tasks, UI buttons for running CodeChecker log.
* Added settings to specify custom args as well as a build command, which can be overridden by commands or tasks.
* Added a couple tests for the backend.
> Integrate `CodeChecker log` into executor

- src/backend/executor/process.ts
Fixes #94.
There were a couple cases where removing the `CodeChecker version` process from the execution queue would never resolve the `checkVersion()` promise.
Since the version check promise wouldn't resolve, the subsequent process is never executed, leading to the UI not updating fully.
> Fix handling of removed processes from the execution queue

- package.json
- src/backend/processor/diagnostics.ts
- src/sidebar/views/reports.ts
Closes #59, closes #40, supersedes and closes #107.
Refactor the report tree's code.
Display depth of report steps.
Group reports by severity levels.
Fixed my comments in #107.
> Refactor report tree

- package.json
- src/backend/executor/bridge.ts
- src/backend/processor/diagnostics.ts
- src/backend/processor/metadata.ts
- src/editor/executor.ts
- src/editor/initialize.ts
- src/utils/config.ts
Fixes #111.
* Refactored the `CodeChecker version` handling, so a version check process couldn't be prematurely killed, leading to a false `CodeChecker not found` notification. (Should be enough to fix the particular issue showing double notifs.)
* Added a toggle to disable version-check related notifications altogether
> Improvements for handling CodeChecker version checks

- src/backend/api.ts
- src/backend/executor/bridge.ts
- src/backend/executor/process.ts
- src/backend/parser/metadata.ts
- src/backend/processor/metadata.ts
- src/backend/types/checkers.ts
- src/backend/types/index.ts
- src/editor/navigation.ts
- src/sidebar/views/reports.ts
- src/test/executor/executor.functional.test.ts
The documentation URLs are fetched by running `CodeChecker checkers` at project load.
> Add `Go to docs` button to sidebar

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Uses the Tests action as dependency instead of doing a copy of its own.
> Fix Deploy action

- package.json
- src/backend/executor/bridge.ts
- src/backend/processor/diagnostics.ts
- src/backend/processor/metadata.ts
- src/editor/diagnostics.ts
- src/editor/editor.ts
- src/editor/executor.ts
- src/editor/initialize.ts
- src/editor/navigation.ts
- src/editor/notifications.ts
- src/extension.ts
- src/sidebar/sidebar_container.ts
- src/sidebar/views/index.ts
- src/sidebar/views/notifications.ts
- src/sidebar/views/overview.ts
- src/sidebar/views/reports.ts
- src/utils/config.ts
- Added a sidebar view to show past notifications
- The notif's actions can still be executed through the sidebar, even if the user disabled pop-up notifications
- Ported all existing notifications to the new system, but did not add any new ones yet
> Notifications overhaul

- src/test/executor/executor.functional.test.ts
The file events apparently did not fire consistently fast enough on CI.
> Extend timeout for file watcher events

- README.md
- package.json
- src/backend/executor/bridge.ts
- src/editor/notifications.ts
- src/sidebar/views/overview.ts
- src/test/executor/executor.functional.test.ts
Requires #123. Reference: #113, Ericsson/CodeChecker#3708
Adds support for CodeChecker 6.22's automatic compilation database detection. If no comp.db. is specified, and there is none in CodeChecker's output folder, the extension will use CodeChecker's autodetection (for 6.22 and above). For 6.21, and the mentioned cases, the behavior remains the same.
Remaining tasks:
- Design and implement commands for building multi-root projects. Currently you can only build either a single file, or the outermost folder via the default commands.
- Support for anayzing 2 or more files without an explicit comp.db. From my reading, `CodeChecker analyze` can only accept a single file or folder as input, so for multiple files we'd need to autodetect common folders, or run the analysis for each file …
> Initial multi-root support

- package.json
- src/backend/executor/bridge.ts
- src/backend/executor/process.ts
- src/editor/executor.ts
- src/editor/notifications.ts
- src/sidebar/views/notifications.ts
- src/sidebar/views/overview.ts
- src/test/executor/executor.functional.test.ts
- yarn.lock
Added notifications for adding CodeChecker log and analyze commands to the queue, and then executing them.
They are mainly displayed on the sidebar, and there's actions for killing the process or removing them from the queue.
> Notifications for the executed processes

- .yarnrc.yml
- yarn_plugins/plugin-list.js
`yarn list` is not an actual command in yarn v2. This patch implements a custom plugin, that adds the command that is needed for pulblishing the extension.
Originally found at:
https://gist.github.com/arendjr/415747652a8c79f12b005ce3cfb2f808
> Add yarn list as a custom plugin

- .github/workflows/deploy.yml
- .github/workflows/package.yml
- .github/workflows/test-commit.yml
- .github/workflows/test.yml
The rewriter for publishing to the Marketplace also needs to rewrite a couple things within `yarn.lock`.
Updated the GH Actions files to use the new output syntax, and refactored tests - they now also test `vsce package` on the plugin.
> Fix vsce rewriting and refactor tests

- src/editor/executor.ts
- src/editor/logger.ts
Requires https://github.com/Ericsson/CodecheckerVSCodePlugin/pull/140 for CI passing.
In some locations, the commands `codechecker.logging.showOutput` and `codechecker.executor.showOutput` were inconsistently used. They are now all `codechecker.executor.showOutput`.
Fixes sidebar commands when CodeChecker is running, among others.
> Fix `codechecker.executor.showOutput` command

- README.md
I have added a note in the README file about the possible conflict between the own built extension and the extension already installed from marketplace.
> Add note for developers about extension conflicts

- README.md
- package.json
- src/editor/diagnostics.ts
Fixes #139. Requires #140 for CI passing.
By default, all CodeChecker bug severities except STYLE are displayed as errors inside the editor. This PR adds a setting to enable changing how each of these severities are displayed.
> Add setting to change how severities are displayed

- src/backend/executor/bridge.ts
- src/backend/executor/process.ts
- src/editor/executor.ts
- src/editor/notifications.ts
- src/test/executor/executor.functional.test.ts
Fixes (partially) #137 
CodeChecker is assumed to output a summary of its analysis in a user-readable manner, on its last stderr line.
This reason is now displayed on the sidebar, if available.
Also added support for differentiating between CodeChecker warnings/errors.
(The full reason is of course shown on hover.)
> Add support for CodeChecker warning/error reasons

- README.md
- package.json
- src/editor/initialize.ts
Added documentation about `make` and `cmake` to the extension's README.
> Improve docs about the compilation database

- README.md
- package.json
- src/backend/executor/bridge.ts
Fixes #150.
I chose the default timeout to be 60s - there's no good default, but in general this timeout should be a last resort to save system resources, in case of an accidentally enabled long-running checker.
> Add analysis timeout parameter
